---
- name: apt-get update
  apt: update_cache=true

# comment out; takes too damn long
# - name: apt-get upgrade
#   apt: upgrade=yes

- name: install python-dev
  apt: name=python-dev state=present

- name: install python-setuptools
  apt: name=python-setuptools state=present

- name: install build-essential
  apt: name=build-essential state=present

- name: install python-pip
  apt: name=python-pip state=present
